"""Trade-specific presentation; all copy and links remain server-rendered."""
import html
H=html.escape

def render_trade(p, meta, production, modal, modal_css, cta, footer, links, schedule):
    t=p['trade']
    jobs=''.join('<span>'+H(j)+'</span>' for j in t['jobs'])
    steps=''.join(f'<li><b>0{i+1}</b><span>{H(s)}</span></li>' for i,s in enumerate(t['steps']))
    offers=[('01','A website worth showing off','Fast, considered design. Clear service pages. An enquiry journey built around the work you want.'),('02','Search visibility with substance','Technical SEO, useful local content and Google Business Profile improvements, scoped to your business.'),('03','Campaigns with a clear destination','Search ads and landing pages that connect a specific service to a relevant customer enquiry.'),('04','A better follow-up process','Enquiry routing, quote reminders and supported integrations that help your team keep the conversation moving.')]
    cards=''.join('<div class="trade-offer"><span>'+n+'</span><h3>'+h+'</h3><p>'+b+'</p></div>' for n,h,b in offers)
    sections=''.join(f'<section class="trade-detail" id="section-{i}"><span class="trade-index">{i+1:02d} / THE DETAILS</span><div><h2>{H(s["heading"])}</h2><p>{H(s["body"])}</p></div></section>' for i,s in enumerate(p['sections']))
    faqs=''.join('<details><summary>'+H(f['question'])+'</summary><p>'+H(f['answer'])+'</p></details>' for f in p['faqs'])
    sources=''.join('<li><a href="'+H(s['url'],quote=True)+'">'+H(s['title'])+'</a></li>' for s in p['sources'])
    return f'''<!doctype html><html lang="en-AU"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f4ead5">{meta(p,production)}<link rel="icon" href="/favicon.svg">{modal_css}<link rel="stylesheet" href="/fonts.css"><link rel="stylesheet" href="/growth.css"><link rel="stylesheet" href="/trades.css"><script src="/events.js" defer></script></head>
<body class="growth-page trade-page trade-{t['theme']}"><a class="skip-link" href="#main-content">Skip to content</a><header class="growth-wrap"><nav class="growth-nav" aria-label="Main"><a href="/">DirectSite</a><a href="/web-design/">Web design</a><a href="/industries/">Industries</a><a href="/services/">Services</a><a class="growth-nav-cta" href="{schedule}" data-book data-placement="nav">Get a free demo →</a></nav></header>
<main id="main-content"><div class="growth-wrap"><nav class="growth-breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a> / <a href="/industries/">Industries</a> / {H(t['label'])}</nav>
<header class="trade-hero"><div class="trade-hero-copy"><p class="growth-kicker">Digital growth for {H(t['label'])}</p><h1>{H(p['h1'])}</h1><p class="growth-answer">{H(p['answer'])}</p><div class="growth-actions">{cta('trade_hero')}<a class="trade-text-link" href="#services">Explore what we can do ↓</a></div></div>
<aside class="trade-art" aria-label="Illustrative customer journey"><div class="trade-art-top"><span>BUILT AROUND YOUR TRADE</span><span aria-hidden="true">↗</span></div><div class="trade-art-scene" aria-hidden="true"><div class="trade-shape shape-one"></div><div class="trade-shape shape-two"></div><div class="trade-shape shape-three"></div><span>{'A better first impression.' if t['theme']=='floor' else 'Every enquiry. A clearer next step.'}</span></div><div class="trade-art-bottom"><p>From interest to enquiry</p><ol>{steps}</ol><small>Example journey · tailored to your business</small></div></aside></header>
<div class="trade-job-strip"><p>Your services. Their next step.</p><div>{jobs}</div></div>
<section class="trade-services" id="services"><div class="trade-section-head"><p class="growth-kicker">A useful website is just the start</p><h2>{H(t['headline'])}</h2><p>{H(t['intro'])}</p></div><div class="trade-offers">{cards}</div><p class="growth-note">Start with the website. Add services as needed. SEO, advertising, integrations and provider fees are scoped separately.</p><a class="trade-text-link" href="/services/">See all DirectSite services →</a></section>
<section class="trade-plan"><div><p class="growth-kicker">The plan for your business</p><h2>Specific to your work.<br>Useful to your customers.</h2></div><p>From what people search to what your team needs to quote, every part of the journey should earn its place.</p></section>
<div class="trade-details">{sections}</div>
<section class="trade-start"><div><p class="growth-kicker">Built before you buy</p><h2>See the direction.<br>Then make the decision.</h2><p>A real website demo within 48 hours. Review it, request changes and agree the price before payment.</p>{cta('trade_bottom')}</div><ol><li><b>01</b><div><h3>Tell us about the work</h3><p>Your services, service area and the jobs you want more of.</p></div></li><li><b>02</b><div><h3>Try your working demo</h3><p>Review it on your phone and request free revisions.</p></div></li><li><b>03</b><div><h3>Choose your next step</h3><p>Approve the scope, or walk away owing $0.</p></div></li></ol></section>
<section class="trade-faq growth-faq"><div><p class="growth-kicker">Before you get started</p><h2>A few useful answers.</h2></div><div>{faqs}</div></section>
<nav class="trade-related" aria-label="Related resources"><h2>Keep exploring</h2>{links(p['related'])}</nav><details class="trade-research"><summary>Research behind this approach</summary><p>Reviewed <time datetime="{p['lastReviewed']}">16 September 2026</time>. These sources inform our recommendations; they are not endorsements. Provider features and requirements can change.</p><ul>{sources}</ul></details>
</div></main>{footer()}{modal}<script src="/demo-form.js" defer></script><script src="/form-accessibility.js" defer></script></body></html>'''
